apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-kubernetes-demo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: kafka-kubernetes-demo
  template:
    metadata:
      labels:
        app: kafka-kubernetes-demo
    spec:
      containers:
      - name: kafka-kubernetes-demo
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-kubernetes-demo-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: kafka-kubernetes-demo
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
