apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: {{ .Values.namespace }}
  #annotations:
   # "helm.sh/hook": post-install,post-upgrade
   # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kafka-topic-creator
          image: confluentinc/cp-kafka:7.0.1
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Kafka..."
              while ! nc -z kafka-service 9092; do sleep 1; done
              echo "Kafka is up. Creating topics..."
              {{- range .Values.topics }}
              kafka-topics --bootstrap-server kafka-service:9092 \
                --create \
                --if-not-exists \
                --topic {{ .name }} \
                --replication-factor {{ .replicationFactor }} \
                --partitions {{ .partitions }};
              {{- end }}
