name: CI - Build and Push Spring Boot Docker Image (Run Number + Latest)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build Spring Boot JAR
      run: mvn clean install

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with dynamic tag
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kafka-kubernetes-demo:${{ env.IMAGE_TAG }} .

    - name: Also tag image as 'latest'
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/kafka-kubernetes-demo:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/kafka-kubernetes-demo:latest

    - name: Push image with dynamic tag
      run: docker push ${{ secrets.DOCKER_USERNAME }}/kafka-kubernetes-demo:${{ env.IMAGE_TAG }}

    - name: Push image with 'latest' tag
      run: docker push ${{ secrets.DOCKER_USERNAME }}/kafka-kubernetes-demo:latest
